[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'npm install',
  'cd client && npm install'
]

[phases.build]
cmds = [
  'cd client && CI=false npm run build'
]

[start]
cmd = 'npm run db:migrate:schema && NODE_ENV=production node server/index.js'
