[build]
builder = "NIXPACKS"
buildCommand = "cd databricks-maturity-assessment && npm install && cd client && rm -rf build node_modules/.cache && npm install && npm run build && cd .."

[deploy]
startCommand = "cd databricks-maturity-assessment && NODE_ENV=production node server/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

